<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9ce3c68-9e04-4da3-96b4-07fba4a04248</elementGuidId>
    <imagePath></imagePath>
    <name>input_searchQuery</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Enter a query with minimum of 2 character(s) to enable search.') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Enter a query with minimum of 2 character(s) to enable search.\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Enter a query with minimum of 2 character(s) to enable search.</value>
        <webElementGuid>e1554a81-41f9-492e-bcd5-2ae31c8bf262</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>e1554a81-41f9-492e-bcd5-2ae31c8bf262</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/TexasInstrument_Production/Page_home/atomicSearchBox_search</value>
        <webElementGuid>e1554a81-41f9-492e-bcd5-2ae31c8bf262</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>e1554a81-41f9-492e-bcd5-2ae31c8bf262</webElementGuid>
    </webElementProperties>
</WebElementEntity>