<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db172c18-ae46-4846-a141-5323f6d7d50d</elementGuidId>
    <imagePath></imagePath>
    <name>button_logIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//button</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#loginbutton button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/TexasInstrument_Production/Page_as/tiButton_logIn</value>
        <webElementGuid>061c492c-f3b3-43c4-a3e6-e6d96ff95f07</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>061c492c-f3b3-43c4-a3e6-e6d96ff95f07</webElementGuid>
    </webElementProperties>
</WebElementEntity>